# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: yuvarset-test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
            echo $MYSQL_HOST
            echo $MYSQL_USER
            echo $MYSQL_PASSWORD
            echo $MYSQL_DB

        env:
            MYSQL_HOST: sql6.freemysqlhosting.net
            MYSQL_USER: sql6458625
            MYSQL_PASSWORD: PpFuFC8nPT
            MYSQL_DB: sql6458625
